services:
  db-mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: smartlogix_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smartlogix-net

  back-despachos:
    image: 992382711706.dkr.ecr.us-east-1.amazonaws.com/back-despachos:latest
    container_name: service_despachos
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/smartlogix_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - db-mysql
    networks:
      - smartlogix-net

  back-ventas:
    image: 992382711706.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
    container_name: service_ventas
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/smartlogix_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - db-mysql
    networks:
      - smartlogix-net

  web_front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_front
    ports:
      - "80:8080"
    networks:
      - smartlogix-net
    depends_on:
      - back-ventas
      - back-despachos

volumes:
  mysql_data:

networks:
  smartlogix-net:
    driver: bridge
